language: node_js
node_js: '6'
deploy:
  provider: heroku
  api_key:
    secure: baiqXkJ9glClVbEcJqKoC3Ixj7HueX8/c0B67oZCIVsfPBb0AcVn4Z1j2mhUT7YJjmDqLz7XwPJWvUlbEE+2QUTwjJhQsFSYk16mAD5NQnLaepz1a1klDGXzsXxLJCXhw1Gl2ck1DjIlD0WD38B1WPEPOUK7dzBwkhjha5FtMMLZuAGsCmyhizpB/RsLEJ3VXw4PV4PjwR1fI8nu1vVI3KqN6oKBbTX00Vk38XU+GB71P24Vzp2Mq190ctf3h58Wv2Lf2mp4rB1+jBF2Rk9EOTSszNE15RCH/N1urXFZO5C1OmvxR/nqOXsQcPTJ8oKsvQmpr2ZgWaQ9nn3oKFyHLnBwKx8Ufa7a9ptRSF4bLO+xForYX7k3XpO8HA73z43E0EuDq8fv3PnVQE2Kc1/NehKlnsFccvnxf/ipgMkqX0qJbqmOChOIkez6S9Bjw6S0SvZKgSJ63YucSAfhQJ2TdH9BVSI6GMIGPAcYCCVT/bBzUjXeeExxgJ9A1xFEVtcUT6zXbnrvsi8jkho7BUcLQN2WvNeTlkb5cSn6TXlgIwy1mtG9wixWDhd9Mjq5r0cqmWUvZIRPcYJFNb7u2+KlQMrR9JgQFfacleDw1IkuwDNQhtWuVmim+aKzWiacgddTlebtvdS4Nh06Sz7g0iNgf+lYduqh1erSOSf0c+T/6c0=
  app: havis-node
  on:
    repo: tzpr/havis
