language: node_js
node_js: '6'
services:
  - mongodb
env:
  - NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: bNMGoZWxckrBIFbMzDkJtRptszuU/Mi6dFeSJPewEAGmTd7OnTD6n9nI/EbakQOpw9Lhby6gqOKhjlRYa3uV/dJomSr0pd9HBQGUMc5SLOlV4+eezhVXVCIkId1hH9l7g1p6Ck20SwTO9hDeB23bsQsqN3DNJUExsb3E9s0FSbe3JnW7ipDTCeW0Gevn2O0lVLL1yhh4QSFx8SAdswRfYNxWYKrmhjMQnzyym0vLDW2LcUbiaZDgBUsqnGTWMCQnPpE8Hi19/794B0PsE04d0aqyzWQLQMqahN1dVZixV05sFMUIr1F851NjeZoDOywZfUWkAOyZ6zF8cO5MjHEacocruNVJGMqBGEQZ/G7E1/oO3PTM6q/tf9S+DeX2AuJ+ZZH4r/BO+Z0NRy4wj8c6nmCGiPGHk+632Xh7X6ffiRjs3V+ASeiZc79gCrLsKuEfjS9YVeMVmk48ThNAYKvRS8PLgq8XihSF11dFD3M5aNcO6dganZrtiWaKctbummTWA8fa6l5ZFsJ7OXxEsx8q80MLD5uw/NQ6ENZDR8XtuVuIFcI97Ft6qeVonk0tctphgUQwfE5vC8U3tN5G137EAySwfhJOa3GPPacBSg8tBwlXKH2KF4NAqK1F86f2XcE1iDPPGg3B7UeNM+GAnvjPX3v7K1nNXDYuBV2pnNyKNWw=
  app: havis-node
  on:
    repo: tzpr/havis
